AllCops:
  Exclude:
    - 'Rakefile'
    - 'filter_param.gemspec'
  TargetRubyVersion: 2.3.0
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 110
  Exclude:
    - "spec/**/*.rb"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
Metrics/MethodLength:
  Exclude:
    - "spec/**/*.rb"