name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
      RAILS_VERSION: ${{ matrix.rails }}

    strategy:
      fail-fast: false
      matrix:
        rails: 
          - '6-0'
          - '6-1'
          - '7-0'
          - '7-1'
          - '7-2'
          - '8-0'
        include:
          - rails: '6-0'
            ruby_version: '2.7'
            bundler_version: 'latest'
          - rails: '6-1'
            ruby_version: '2.7'
            bundler_version: 'latest'
          - rails: '7-0'
            ruby_version: '2.7'
            bundler_version: 'latest'
          - rails: '7-1'
            ruby_version: '2.7'
            bundler_version: 'latest'
          - rails: '7-2'
            ruby_version: '3.1'
            bundler_version: 'latest'
          - rails: '8-0'
            ruby_version: '3.2'
            bundler_version: 'latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler: ${{ matrix.bundler_version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
